package com.panaromarestaurant.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity // Declares this class as a JPA entity, meaning it will be persisted to a table in the database
@Table(name = "submenu_category") // Specifies the database table name this entity maps to: "submenu_category"

@Data // Lombok annotation that generates all the usual boilerplate code: getters, setters, equals, hashCode, and toString methods
@AllArgsConstructor // Lombok annotation to automatically generate a constructor that takes all fields as arguments
@NoArgsConstructor // Lombok annotation to automatically generate a no-argument constructor (required by JPA and some frameworks)

public class SubMenuCategory {

    @Id // Identifies this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the ID to be auto-generated by the database (usually using AUTO_INCREMENT)
    private Integer id; // Unique identifier for the submenu category

    // @Column(name = "name") // Optional: Use if the actual column name in the DB differs from the field name
    private String name; // Name of the submenu category (e.g., "Starters", "Main Course", "Drinks")
}
